### ISSUE TITLE
try easytranslate for free

### ISSUE THREAD

**Issue by raphaelB4** [seejohnrun/easy_translate#37]
Hello,  I am getting interested to try easytranslate because it seems quite easy to use. But because I am just a student I don't feel very confident in creating a billing account. Do you know if there is a way to use it moderately for small personal projects without a billing account?
Thanks

**Comment by seejohnrun** [comment]
Unfortunately google translate is for paid use only at this point (not when this library was written).

Maybe check out https://ctrlq.org/code/19909-google-translate-api or something like that?
