### ISSUE TITLE
NameError uninitialized constant EasyTranslate::Translation::TranslationRequest::LANGUAGES

### ISSUE THREAD

**Issue by siaw23** [seejohnrun/easy_translate#41]
For some reason I'm getting this error: 

`NameError uninitialized constant EasyTranslate::Translation::TranslationRequest::LANGUAGES`

on production and I am not sure why this is happening. 

I have my app dockerised and using version `easy_translate (0.5.0)`. Gem was installed via bundler.

Maybe someone has some idea or had this issue before and managed to fix it?

**Comment by seejohnrun** [comment]
Weird - just tested against that version and I'm not seeing that error.

What version of Ruby are you using?

**Comment by seejohnrun** [comment]
I'm currently on ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]

**Comment by siaw23** [comment]
i'm on `ruby 2.3.0`. it possibly could be from my side. i'll dive deeper with debugging just in case it's not the gem's fault. @seejohnrun

**Comment by siaw23** [comment]
OK here's a part of the full stack trace. I believe this gem depends on something else that's down at the moment. Right? @seejohnrun 

```
EasyTranslate::EasyTranslateException: The service is unavailable at this time.
  from easy_translate/request.rb:47:in `perform_raw'
  from easy_translate/translation.rb:34:in `request_translations'
  from easy_translate/threadable.rb:24:in `block in threaded_process'
  from easy_translate/threadable.rb:24:in `map'
  from easy_translate/threadable.rb:24:in `threaded_process'
  from easy_translate/translation.rb:20:in `translate'
  from app/models/image_response.rb:265:in `block in translate_name!'
  from statsd/instrument.rb:284:in `block in measure'
  from statsd/instrument.rb:53:in `duration'
  from statsd/instrument.rb:284:in `measure'
```

**Comment by seejohnrun** [comment]
This sounds like a temporary issue to me - can you provide some more on how you're calling `translate` and what options you're passing?

This seems different and disconnected from the issue you originally reported - is that resolved now?

**Comment by seejohnrun** [comment]
Closing this for now - let us know if there's an ongoing issue here
