### ISSUE TITLE
EasyTranslate::EasyTranslateException (Daily Limit Exceeded)

### ISSUE THREAD

**Issue by guilhermemaranhao** [seejohnrun/easy_translate#46]
Hi,

How can I solve this issue?

Thanks,

Guilherme

**Comment by guilhermemaranhao** [comment]
Is there anything to do specifically with the gem or with my google application account?

**Comment by seejohnrun** [comment]
This has to do with your google account and the amount of free translations you can do before they limit you. Thanks!

**Comment by guilhermemaranhao** [comment]
Thank you
